<?php
session_start();
echo '<nav class="navbar">';
echo '<ul>';
echo '<li><a href="client.php">Home <i class="fas fa-home"></i></a></li>';
echo '<li class="dropdown">';
echo '<a href="#">Trainings <i class="fas fa-bars"></i></a>';
echo '<div class="dropdown-content">';
echo '<a href="segmentation.php">Segmentation Workshop</a>';
echo '<a href="cocreation.php">Co-Creation Workshop</a>';
echo '<a href="brainstorm.php">Consumer Brainstorm Workshop</a>';
echo '<a href="activation.php">Team Activation Workshop</a>';
echo '</div>';
echo '</li>';
echo '<li><a href="request.php">Request <i class="fas fa-bell"></i></a></li>';
echo '<li><a href="#">Booking <i class="fas fa-cart-plus"></i></a></li>';
echo '<li><a href="clientchat.php">Chat<i class="fas fa-comments"></i></a></li>';
echo '<li class="dropdown">';
echo '<a href="profile.php">Profile <i class="fas fa-user"></i></a>';
echo '<div class="dropdown-content">';
echo '<a href="change_password.php">Change Password</a>';
echo '<a href="delete_acc.php">Delete Account</a>';
echo '</div>';
echo '</li>';
echo '<li><a href="login.php">Logout <i class="fas fa-user-circle"></i></a></li>';
echo '</ul>';
echo '</nav>';
